# --- Analysis dashboard ---
X_VAR_DROPDOWN = "x-var-dropdown"
Y_VAR_DROPDOWN = "y-var-dropdown"
SINGLE_DROPDOWN = "single-dropdown"
SELECT_ALL_BUTTON = "select-all-button"
MORPHDRAIN_LINE_CHART = "morphdrain-line-chart"
IMAGE_SLICE = "image-slice"
TIMELOG_LINE_CHART = "timelog-line-chart"
SCAL_LINE_CHART = "SCAL-line-chart"
SUBPHASE_LINE_CHART = "subphase-line-chart"
SLIDER = "slider"
VTK_3D_VIS = "vtk-3d-vis"

# --- Setup dashboard: geometry page ---
GEOMETRY_SOURCE_RADIO = "geometry-source-radio"
GEOMETRY_REMOTE_PATH = "geometry-remote-path"
GEOMETRY_UPLOAD = "geometry-upload"
GEOMETRY_NX = "geometry-nx"
GEOMETRY_NY = "geometry-ny"
GEOMETRY_NZ = "geometry-nz"
GEOMETRY_LOAD_BTN = "geometry-load-btn"
GEOMETRY_INFO = "geometry-info"
GEOMETRY_SLICE_AXIS = "geometry-slice-axis"
GEOMETRY_SLICE_INDEX = "geometry-slice-index"
GEOMETRY_SLICE = "geometry-slice"
FLOW_F_X = "flow-f-x"
FLOW_F_Y = "flow-f-y"
FLOW_F_Z = "flow-f-z"

# --- Setup dashboard: domain config ---
DOMAIN_NPROC = "domain-nproc"
DOMAIN_N_SUBDOM = "domain-n-subdom"
DOMAIN_VOXLEN = "domain-voxlen"
DOMAIN_BC = "domain-bc"
DOMAIN_WRITE_VALUES = "domain-write-values"
DOMAIN_COMPONENT_LABELS = "domain-component-labels"
DOMAIN_READ_VALUES_DISPLAY = "domain-read-values-display"
DOMAIN_READ_VALUES = "domain-read-values"
DOMAIN_FILENAME = "domain-filename"
DOMAIN_OFFSET = "domain-offset"
DOMAIN_BC_PARAMS = "domain-bc-params"
DOMAIN_DIN = "domain-din"
DOMAIN_DOUT = "domain-dout"
DOMAIN_FLUX = "domain-flux"
VALIDATION_BADGE = "validation-badge"
ANALYSIS_VIS_INTERVAL = "analysis-vis-interval"
ANALYSIS_N_THREADS = "analysis-n-threads"
ANALYSIS_RESTART_INTERVAL = "analysis-restart-interval"

# --- Setup dashboard: model config ---
MODEL_SELECTOR = "model-selector"
COLOR_TAU_A = "color-tau-a"
COLOR_TAU_B = "color-tau-b"
COLOR_RHO_A = "color-rho-a"
COLOR_RHO_B = "color-rho-b"
COLOR_ALPHA = "color-alpha"
COLOR_BETA = "color-beta"
COLOR_CAP_NUM = "color-cap-num"
COLOR_TIMESTEP_MAX = "color-timestep-max"
COLOR_RESTART = "color-restart"
COLOR_PROTOCOL = "color-protocol"
COLOR_INLET_LAYERS = "color-inlet-layers"
COLOR_OUTLET_LAYERS = "color-outlet-layers"
COLOR_COMPONENT_AFFINITY = "color-component-affinity"
FA_MAX_STEADY = "fa-max-steady"
FA_MIN_STEADY = "fa-min-steady"
FA_FF_INCREMENT = "fa-ff-increment"
FA_MASS_FRACTION = "fa-mass-fraction"
FA_ENDPOINT_THRESH = "fa-endpoint-thresh"
ANALYSIS_INTERVAL = "analysis-interval"
ANALYSIS_SUBPHASE_INTERVAL = "analysis-subphase-interval"
VIS_SAVE_8BIT = "vis-save-8bit"
VIS_SAVE_PHASE = "vis-save-phase"
VIS_SAVE_PRESSURE = "vis-save-pressure"
VIS_SAVE_VELOCITY = "vis-save-velocity"

# --- Setup dashboard: create sim dir ---
REMOTE_BASE_PATH = "remote-base-path"
SIM_NAME_INPUT = "sim-name-input"
PREVIEW_INPUT_DB_BTN = "preview-input-db-btn"
INPUT_DB_PREVIEW_MODAL = "input-db-preview-modal"
INPUT_DB_PREVIEW_CONTENT = "input-db-preview-content"
CREATE_SIM_BTN = "create-sim-btn"
UPLOAD_PROGRESS = "upload-progress"
UPLOAD_PROGRESS_INTERVAL = "upload-progress-interval"
CREATE_STATUS = "create-status"
