# --- Analysis dashboard ---
X_VAR_DROPDOWN = "x-var-dropdown"
Y_VAR_DROPDOWN = "y-var-dropdown"
SINGLE_DROPDOWN = "single-dropdown"
SELECT_ALL_BUTTON = "select-all-button"
MORPHDRAIN_LINE_CHART = "morphdrain-line-chart"
IMAGE_SLICE = "image-slice"
TIMELOG_LINE_CHART = "timelog-line-chart"
SCAL_LINE_CHART = "SCAL-line-chart"
SUBPHASE_LINE_CHART = "subphase-line-chart"
SLIDER = "slider"
VTK_3D_VIS = "vtk-3d-vis"

# --- Setup dashboard: geometry page ---
GEOMETRY_SOURCE_RADIO = "geometry-source-radio"
GEOMETRY_REMOTE_PATH = "geometry-remote-path"
GEOMETRY_UPLOAD = "geometry-upload"
GEOMETRY_NX = "geometry-nx"
GEOMETRY_NY = "geometry-ny"
GEOMETRY_NZ = "geometry-nz"
GEOMETRY_LOAD_BTN = "geometry-load-btn"
GEOMETRY_INFO = "geometry-info"
GEOMETRY_SLICE_AXIS = "geometry-slice-axis"
GEOMETRY_SLICE_INDEX = "geometry-slice-index"
GEOMETRY_SLICE = "geometry-slice"
GEOMETRY_SLICE_VIEWER = "geometry-slice-viewer"
FLOW_F_X = "flow-f-x"
FLOW_F_Y = "flow-f-y"
FLOW_F_Z = "flow-f-z"

# --- Setup dashboard: domain config ---
DOMAIN_NPROC = "domain-nproc"
DOMAIN_N_SUBDOM = "domain-n-subdom"
DOMAIN_VOXLEN = "domain-voxlen"
DOMAIN_BC = "domain-bc"
DOMAIN_WRITE_VALUES = "domain-write-values"
DOMAIN_COMPONENT_LABELS = "domain-component-labels"
DOMAIN_READ_VALUES_DISPLAY = "domain-read-values-display"
DOMAIN_READ_VALUES = "domain-read-values"
DOMAIN_FILENAME = "domain-filename"
DOMAIN_OFFSET = "domain-offset"
DOMAIN_BC_PARAMS = "domain-bc-params"
DOMAIN_DIN = "domain-din"
DOMAIN_DOUT = "domain-dout"
DOMAIN_FLUX = "domain-flux"
DOMAIN_INLET_LAYERS = "domain-inlet-layers"
DOMAIN_OUTLET_LAYERS = "domain-outlet-layers"
DOMAIN_INLET_LAYERS_PHASE = "domain-inlet-layers-phase"
DOMAIN_OUTLET_LAYERS_PHASE = "domain-outlet-layers-phase"
VALIDATION_BADGE = "validation-badge"
ANALYSIS_VIS_INTERVAL = "analysis-vis-interval"
ANALYSIS_N_THREADS = "analysis-n-threads"
ANALYSIS_RESTART_INTERVAL = "analysis-restart-interval"
ANALYSIS_RESTART_FILENAME = "analysis-restart-filename"
# --- Setup dashboard: model config ---
MODEL_SELECTOR = "model-selector"
COLOR_TAU_A = "color-tau-a"
COLOR_TAU_B = "color-tau-b"
COLOR_RHO_A = "color-rho-a"
COLOR_RHO_B = "color-rho-b"
COLOR_ALPHA = "color-alpha"
COLOR_BETA = "color-beta"
COLOR_CAP_NUM = "color-cap-num"
COLOR_TIMESTEP_MAX = "color-timestep-max"
COLOR_RESTART = "color-restart"
COLOR_PROTOCOL = "color-protocol"
COLOR_INLET_LAYERS = "color-inlet-layers"
COLOR_OUTLET_LAYERS = "color-outlet-layers"
COLOR_COMPONENT_AFFINITY = "color-component-affinity"
FA_MAX_STEADY = "fa-max-steady"
FA_MIN_STEADY = "fa-min-steady"
FA_FF_INCREMENT = "fa-ff-increment"
FA_MASS_FRACTION = "fa-mass-fraction"
FA_ENDPOINT_THRESH = "fa-endpoint-thresh"
FA_FF_EPSILON = "fa-ff-epsilon"
FA_SKIP_TIMESTEPS = "fa-skip-timesteps"
ANALYSIS_INTERVAL = "analysis-interval"
ANALYSIS_SUBPHASE_INTERVAL = "analysis-subphase-interval"
VIS_SAVE_8BIT = "vis-save-8bit"
VIS_SAVE_PHASE = "vis-save-phase"
VIS_SAVE_PRESSURE = "vis-save-pressure"
VIS_SAVE_VELOCITY = "vis-save-velocity"

# --- Setup dashboard: create sim dir ---
REMOTE_BASE_PATH = "remote-base-path"
SIM_NAME_INPUT = "sim-name-input"
PREVIEW_INPUT_DB_BTN = "preview-input-db-btn"
INPUT_DB_PREVIEW_MODAL = "input-db-preview-modal"
INPUT_DB_PREVIEW_CONTENT = "input-db-preview-content"
CREATE_SIM_BTN = "create-sim-btn"
UPLOAD_PROGRESS = "upload-progress"
UPLOAD_PROGRESS_INTERVAL = "upload-progress-interval"
CREATE_STATUS = "create-status"

# --- Setup dashboard: session persistence ---
GEOMETRY_SESSION_STORE = "geometry-session-store"
GEOMETRY_ARRAY_STORE = "geometry-array-store"
GEOMETRY_AUTOSAVE_INTERVAL = "geometry-autosave-interval"
LOAD_NEW_GEOMETRY_BTN = "load-new-geometry-btn"

# --- Analysis dashboard: presimulation page ---
PRESIM_SLICE_AXIS = "presim-slice-axis"
PRESIM_SLICE_INDEX = "presim-slice-index"
PRESIM_X_COL = "presim-x-col"
PRESIM_Y_COL = "presim-y-col"
PRESIM_GEOMETRY_STORE = "presim-geometry-store"
PRESIM_CSV_STORE = "presim-csv-store"

# --- Analysis dashboard: input file page ---
ANALYSIS_INPUT_DB_CONTENT = "analysis-input-db-content"
ANALYSIS_INPUT_DB_STORE = "analysis-input-db-store"
ANALYSIS_INPUT_EDIT_BTN = "analysis-input-edit-btn"
ANALYSIS_INPUT_SAVE_BTN = "analysis-input-save-btn"
ANALYSIS_INPUT_TEXTAREA = "analysis-input-textarea"
ANALYSIS_INPUT_EDIT_SECTION = "analysis-input-edit-section"
ANALYSIS_INPUT_STATUS = "analysis-input-status"

# --- Tooltip targets: geometry page (Load Geometry) ---
TOOLTIP_NX = "tooltip-nx"
TOOLTIP_NY = "tooltip-ny"
TOOLTIP_NZ = "tooltip-nz"
TOOLTIP_REMOTE_PATH = "tooltip-remote-path"
TOOLTIP_FX = "tooltip-fx"
TOOLTIP_FY = "tooltip-fy"
TOOLTIP_FZ = "tooltip-fz"
TOOLTIP_SLICE_AXIS = "tooltip-slice-axis"
TOOLTIP_SLICE_INDEX = "tooltip-slice-index"

# --- Tooltip targets: Domain Config ---
TOOLTIP_NPROC = "tooltip-nproc"
TOOLTIP_N_SUBDOM = "tooltip-n-subdom"
TOOLTIP_VOXLEN = "tooltip-voxlen"
TOOLTIP_BC = "tooltip-bc"
TOOLTIP_DIN = "tooltip-din"
TOOLTIP_DOUT = "tooltip-dout"
TOOLTIP_FLUX = "tooltip-flux"
TOOLTIP_INLET_LAYERS_PHASE = "tooltip-inlet-layers-phase"
TOOLTIP_OUTLET_LAYERS_PHASE = "tooltip-outlet-layers-phase"
TOOLTIP_READ_VALUES = "tooltip-read-values"
TOOLTIP_WRITE_VALUES = "tooltip-write-values"
TOOLTIP_COMPONENT_LABELS = "tooltip-component-labels"
TOOLTIP_FILENAME = "tooltip-filename"
TOOLTIP_OFFSET = "tooltip-offset"

# --- Tooltip targets: Model Config ---
TOOLTIP_MODEL_SELECTOR = "tooltip-model-selector"
TOOLTIP_TAU_A = "tooltip-tau-a"
TOOLTIP_TAU_B = "tooltip-tau-b"
TOOLTIP_RHO_A = "tooltip-rho-a"
TOOLTIP_RHO_B = "tooltip-rho-b"
TOOLTIP_ALPHA = "tooltip-alpha"
TOOLTIP_BETA = "tooltip-beta"
TOOLTIP_CAP_NUM = "tooltip-cap-num"
TOOLTIP_TIMESTEP_MAX = "tooltip-timestep-max"
TOOLTIP_PROTOCOL = "tooltip-protocol"
TOOLTIP_RESTART = "tooltip-restart"
TOOLTIP_RESTART_FILENAME = "tooltip-restart-filename"
TOOLTIP_INLET_LAYERS = "tooltip-inlet-layers"
TOOLTIP_OUTLET_LAYERS = "tooltip-outlet-layers"
TOOLTIP_COMPONENT_AFFINITY = "tooltip-component-affinity"
TOOLTIP_FA_MAX_STEADY = "tooltip-fa-max-steady"
TOOLTIP_FA_MIN_STEADY = "tooltip-fa-min-steady"
TOOLTIP_FA_FF_INCREMENT = "tooltip-fa-ff-increment"
TOOLTIP_FA_MASS_FRACTION = "tooltip-fa-mass-fraction"
TOOLTIP_FA_ENDPOINT_THRESH = "tooltip-fa-endpoint-thresh"
TOOLTIP_FA_FF_EPSILON = "tooltip-fa-ff-epsilon"
TOOLTIP_FA_SKIP_TIMESTEPS = "tooltip-fa-skip-timesteps"
TOOLTIP_PERM_TAU = "tooltip-perm-tau"
TOOLTIP_PERM_TOLERANCE = "tooltip-perm-tolerance"
TOOLTIP_PERM_TIMESTEP_MAX = "tooltip-perm-timestep-max"
TOOLTIP_MORPH_OPERATION = "tooltip-morph-operation"
TOOLTIP_MORPH_SW = "tooltip-morph-sw"
MORPH_SW = "morph-sw"
TOOLTIP_ANALYSIS_INTERVAL = "tooltip-analysis-interval"
TOOLTIP_SUBPHASE_INTERVAL = "tooltip-subphase-interval"
TOOLTIP_VIS_INTERVAL = "tooltip-vis-interval"
TOOLTIP_N_THREADS = "tooltip-n-threads"
TOOLTIP_RESTART_INTERVAL = "tooltip-restart-interval"
TOOLTIP_SAVE_8BIT = "tooltip-save-8bit"
TOOLTIP_SAVE_PHASE = "tooltip-save-phase"
TOOLTIP_SAVE_PRESSURE = "tooltip-save-pressure"
TOOLTIP_SAVE_VELOCITY = "tooltip-save-velocity"

# --- Tooltip targets: Create Sim Dir ---
TOOLTIP_REMOTE_BASE_PATH = "tooltip-remote-base-path"
TOOLTIP_SIM_NAME = "tooltip-sim-name"
